### ISSUE TITLE
Wrong Import & Variable Names

### ISSUE THREAD

**Issue by oshando** [hobbit-project/java-sdk-example#2]
I have compilation errors caused by the BenchmarkController, ExampleBenchmarkTest and ExampleSystemTest classes. These classes import the import the org.hobbit.sdk.examples.examplebenchmark.docker.ExampleDockersBuilder but the actual implementation is in 
org.hobbit.sdk.examples.dummybenchmark.docker.DummyDockersBuilder. They also use don't use the image names defined in org.hobbit.sdk.examples.examplebenchmark.Constants.java.

**Comment by smirnp** [comment]
Please check the actual version of the code. It should be fixed since yesterday.

**Comment by smirnp** [comment]
Not actual anymore
