### ISSUE TITLE
 Issues with instructions of using java-sdk-example

### ISSUE THREAD

**Issue by Kleanthi** [hobbit-project/java-sdk-example#6]
Here are some issues I found when I tried to follow the [instructions](https://github.com/hobbit-project/java-sdk) to install and run sdk-example. 

**Please note that my intention was to execute an experiment using an existing benchmark and an existing system using my laptop with the following hardware specs:**
`Architecture:          x86_64`
`CPU op-mode(s):        32-bit, 64-bit`
`Byte Order:            Little Endian`
`CPU(s):                4`
`Model name:            Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz`
`CPU MHz:               1698.785`
`CPU max MHz:           3400.0000`
`CPU min MHz:           1200.0000`

1. The link in the sentence `The added value of the Java SDK against standart HOBBIT approach decribed here.`  is not working. Also decribed -> described

2. In order for someone to add `127.0.0.1 rabbit` in the /etc/hosts file, they must be root.

3. Please mention that in order to execute `mvn validate` the user must be in the java-sdk-example folder.

4. `... method from ExampleBenchmarkTest` the link is not working.

5. `...the contents of the ExampleDockersBuilder` the link is not working.

6. `... for ExampleDockersBuilder for particular components in ExampleBenchmarkDockerizedTest` the link is not working.

7. `...Run the buildImages() method from ExampleBenchmarkDockerizedTest ` the link is not working.

8. `...method from ExampleBenchmarkDockerizedTest).` the link is not working.

9.  the sources filder -> the source folders

**Comment by smirnp** [comment]
Thank you for your comments! I have fixed  missing links as well as refreshed the code.
